name: Backend Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [{{ cookiecutter.github_action_python_test_versions }}]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: {{ "${{ matrix.python-version }}" }}
    - name: "Install Dependencies"
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
